/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SellYourCarRouteImport } from './routes/sell-your-car'
import { Route as ImportServicesRouteImport } from './routes/import-services'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarsIndexRouteImport } from './routes/cars.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CarsSlugRouteImport } from './routes/cars.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SellYourCarRoute = SellYourCarRouteImport.update({
  id: '/sell-your-car',
  path: '/sell-your-car',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportServicesRoute = ImportServicesRouteImport.update({
  id: '/import-services',
  path: '/import-services',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsSlugRoute = CarsSlugRouteImport.update({
  id: '/cars/$slug',
  path: '/cars/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/import-services': typeof ImportServicesRoute
  '/sell-your-car': typeof SellYourCarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cars/': typeof CarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/import-services': typeof ImportServicesRoute
  '/sell-your-car': typeof SellYourCarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/cars': typeof CarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/import-services': typeof ImportServicesRoute
  '/sell-your-car': typeof SellYourCarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cars/': typeof CarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/import-services'
    | '/sell-your-car'
    | '/sitemap.xml'
    | '/admin/login'
    | '/cars/$slug'
    | '/admin/'
    | '/cars/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/import-services'
    | '/sell-your-car'
    | '/sitemap.xml'
    | '/admin/login'
    | '/cars/$slug'
    | '/admin'
    | '/cars'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/import-services'
    | '/sell-your-car'
    | '/sitemap.xml'
    | '/admin/login'
    | '/cars/$slug'
    | '/admin/'
    | '/cars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ImportServicesRoute: typeof ImportServicesRoute
  SellYourCarRoute: typeof SellYourCarRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CarsSlugRoute: typeof CarsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CarsIndexRoute: typeof CarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-your-car': {
      id: '/sell-your-car'
      path: '/sell-your-car'
      fullPath: '/sell-your-car'
      preLoaderRoute: typeof SellYourCarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-services': {
      id: '/import-services'
      path: '/import-services'
      fullPath: '/import-services'
      preLoaderRoute: typeof ImportServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$slug': {
      id: '/cars/$slug'
      path: '/cars/$slug'
      fullPath: '/cars/$slug'
      preLoaderRoute: typeof CarsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ImportServicesRoute: ImportServicesRoute,
  SellYourCarRoute: SellYourCarRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  CarsSlugRoute: CarsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  CarsIndexRoute: CarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
